from datetime import datetime

from sqlmodel import Field, SQLModel


# Database Model
class Attendance(SQLModel, table=True):
    id: int | None = Field(default=None, primary_key=True)
    employee_id: int = Field(index=True, nullable=False)
    check_in_time: datetime | None = Field(default=None, nullable=True)
    check_out_time: datetime | None = Field(default=None, nullable=True)
    date: str = Field(index=True, nullable=False)  # YYYY-MM-DD format
    status: str = Field(
        default="pending", nullable=False
    )  # pending, present, absent, late
    notes: str | None = Field(default=None, max_length=500, nullable=True)
    created_at: datetime = Field(default_factory=datetime.now, nullable=False)
    updated_at: datetime = Field(default_factory=datetime.now, nullable=False)


class AttendanceBase(SQLModel):
    """
    Base attendance schema with shared fields.
    """

    employee_id: int = Field(gt=0)
    date: str = Field(min_length=10, max_length=10)  # YYYY-MM-DD format
    status: str = Field(default="pending", max_length=50)
    notes: str | None = Field(default=None, max_length=500)


class CheckInRequest(SQLModel):
    """
    Schema for employee check-in request.
    """

    employee_id: int = Field(gt=0)


class CheckOutRequest(SQLModel):
    """
    Schema for employee check-out request.
    """

    employee_id: int = Field(gt=0)


class AttendanceCreate(AttendanceBase):
    """
    Schema for creating a new attendance record (manual entry).
    Inherits all required fields from AttendanceBase.
    """

    check_in_time: datetime | None = Field(default=None)
    check_out_time: datetime | None = Field(default=None)


class AttendanceUpdate(SQLModel):
    """
    Schema for updating an existing attendance record.
    All fields are optional to support partial updates.
    """

    employee_id: int | None = Field(default=None, gt=0)
    check_in_time: datetime | None = Field(default=None)
    check_out_time: datetime | None = Field(default=None)
    date: str | None = Field(default=None, min_length=10, max_length=10)
    status: str | None = Field(default=None, max_length=50)
    notes: str | None = Field(default=None, max_length=500)


class AttendancePublic(AttendanceBase):
    """
    Schema for attendance responses.
    Includes the id field and timestamps that are generated by the database.
    """

    id: int
    check_in_time: datetime | None = None
    check_out_time: datetime | None = None
    created_at: datetime
    updated_at: datetime


# class DailyCheck(SQLModel):
#     employee_id: int


class MonthlySummary(SQLModel):
    """
    Schema for monthly attendance summary.
    Provides aggregated attendance data for a specific employee and month.
    """

    employee_id: int
    month: str  # YYYY-MM format
    total_days_worked: int
    total_present: int
    total_absent: int
    total_late: int
    working_hours: float
    records: list[AttendancePublic] = []
